- name: Install httpd web server
  yum: name=httpd state=installed
  when: ansible_distribution == "CentOS"
  notify: Restart HTTPD
  
- name: Install apache web server
  apt: name=apache2 state=installed
  when: ansible_distribution == "Ubuntu"  
  notify: Restart APACHE2
  
- name: Copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html
    
- name: Copy sample.html from template
  template: 
    src: sample.j2
    dest: /var/www/html/sample.html
    
- name: Download {{PROJECT}}
  get_url:
    url: "{{URL}}"
    dest: /var/www/html/ecommerce.tgz
    
- name: Extract {{PROJECT}}
  unarchive: 
    src: /var/www/html/ecommerce.tgz
    dest: /var/www/html/
    remote_src: yes
    
- name: Create Virtual Host
  template: 
    src: virt.conf
    dest: /etc/httpd/conf.d/virt.conf
  when: ansible_distribution == "CentOS"
  notify: Restart HTTPD
  
- name: Create Virtual Host
  template: 
    src: virt.conf
    dest: /etc/apache2/sites-enabled/001-virt.conf
  when: ansible_distribution == "Ubuntu"
  notify: Restart APACHE2
    
    
    
    
    
    
    
    
    