- hosts: all
  become: true
  tasks: 
   - name: Install Httpd Web Server
     yum: name=httpd state=installed
     when: ansible_pkg_mgr == "yum"

   - name: Install Apache Web Server
     apt: name=apache2 state=installed
     when: ansible_pkg_mgr == "apt"

   - name: Start Web Server
     service: name=httpd state=started
     when: ansible_distribution == "CentOS"

   - name: Start Apache Web Server 
     service: name=apache2 state=started
     when: ansible_distribution == "Ubuntu" 
